"""
Unit tests for ForgeAI Agent Foundation (Phase 4A).
Validates BaseAgent lifecycle, AgentContext, AgentResult, ArtifactDraft,
schemas, structured errors, retry metadata, timing, and provider abstraction.
"""

import pytest
from typing import Any, Dict, List, Tuple
from pydantic import BaseModel, Field

from app.ai.agents import (
    BaseAgent,
    AgentContext,
    AgentResult,
    ArtifactDraft,
    AgentExecutionError,
    DeterministicMockProvider,
    LLMProvider,
)
from app.ai.agents.utils import sanitize_payload


# ---------------------------------------------------------------------------
# Test Schemas and Dummy Agent Implementation
# ---------------------------------------------------------------------------

class SampleInputSchema(BaseModel):
    prompt: str = Field(..., min_length=5)
    tech_stack: Dict[str, Any] = Field(default_factory=dict)
    shared_state: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class SampleOutputSchema(BaseModel):
    summary: str = Field(..., min_length=3)
    score: int = Field(..., ge=0, le=100)


class DummySpecialistAgent(BaseAgent):
    agent_name = "DummySpecialistAgent"
    version = "1.0.0"
    description = "Test agent for foundation validation"
    input_schema = SampleInputSchema
    output_schema = SampleOutputSchema

    def execute(
        self,
        context: AgentContext,
        validated_input: Dict[str, Any],
    ) -> Tuple[Dict[str, Any], List[ArtifactDraft]]:
        # Check special trigger prompts for testing different failure paths
        prompt = validated_input["prompt"]

        if "trigger_unhandled" in prompt:
            raise RuntimeError("Simulated unexpected crash")

        if "trigger_bad_output" in prompt:
            # Score out of bounds (< 0) to trigger output_validation error
            return {"summary": "Bad", "score": -10}, []

        if "trigger_domain_error" in prompt:
            raise AgentExecutionError(
                message="Domain rule violation",
                agent_name=self.agent_name,
                error_code="RULE_VIOLATION",
                stage="execution",
                details={"reason": "simulated_violation"},
                retryable=True,
            )

        artifacts = [
            ArtifactDraft(
                artifact_type="requirements",
                file_path="docs/SPEC.md",
                content=f"# Specifications for {prompt}\nGenerated successfully.",
                language="markdown",
                metadata={"test": True},
            )
        ]
        return {"summary": f"Processed: {prompt[:20]}", "score": 95}, artifacts


# ---------------------------------------------------------------------------
# Test Cases
# ---------------------------------------------------------------------------

def test_agent_valid_input_and_execution():
    """Test successful agent run with valid input and output schema validation."""
    agent = DummySpecialistAgent()
    context = AgentContext(
        workflow_id="wf-123",
        project_id="proj-456",
        prompt="Build an enterprise CRM platform",
        tech_stack={"backend": "FastAPI", "database": "PostgreSQL"},
    )

    result = agent.run(context)

    assert result.success is True
    assert result.agent_name == "DummySpecialistAgent"
    assert result.version == "1.0.0"
    assert result.error is None
    assert result.data["score"] == 95
    assert "Processed: Build an enterprise" in result.data["summary"]
    assert len(result.artifacts) == 1
    assert result.execution_time_ms >= 0


def test_agent_invalid_input_validation():
    """Test that input failing schema constraints produces a structured failure."""
    agent = DummySpecialistAgent()
    # Prompt is too short (< 5 chars), violating SampleInputSchema
    context = AgentContext(
        workflow_id="wf-123",
        project_id="proj-456",
        prompt="Hi",
    )

    result = agent.run(context)

    assert result.success is False
    assert result.error is not None
    assert "Input validation failed" in result.error
    assert result.error_details["error_code"] == "INVALID_AGENT_INPUT"
    assert result.error_details["stage"] == "input_validation"
    assert result.error_details["retryable"] is False
    assert len(result.artifacts) == 0


def test_agent_invalid_output_validation():
    """Test that invalid output generated by an agent is caught by output schema validation."""
    agent = DummySpecialistAgent()
    context = AgentContext(
        workflow_id="wf-123",
        project_id="proj-456",
        prompt="trigger_bad_output: this prompt will cause agent to return score < 0",
    )

    result = agent.run(context)

    assert result.success is False
    assert result.error is not None
    assert "Output validation failed" in result.error
    assert result.error_details["error_code"] == "INVALID_AGENT_OUTPUT"
    assert result.error_details["stage"] == "output_validation"
    assert result.error_details["retryable"] is True


def test_agent_structured_domain_failure():
    """Test that an explicit AgentExecutionError is caught with stage and details preserved."""
    agent = DummySpecialistAgent()
    context = AgentContext(
        workflow_id="wf-123",
        project_id="proj-456",
        prompt="trigger_domain_error: deliberate domain violation",
    )

    result = agent.run(context)

    assert result.success is False
    assert "Domain rule violation" in result.error
    assert result.error_details["error_code"] == "RULE_VIOLATION"
    assert result.error_details["stage"] == "execution"
    assert result.error_details["details"]["reason"] == "simulated_violation"
    assert result.error_details["retryable"] is True


def test_agent_unhandled_exception_safety():
    """Test that unhandled exceptions are caught safely without crashing the orchestrator."""
    agent = DummySpecialistAgent()
    context = AgentContext(
        workflow_id="wf-123",
        project_id="proj-456",
        prompt="trigger_unhandled exception in execution",
    )

    result = agent.run(context)

    assert result.success is False
    assert "Simulated unexpected crash" in result.error
    assert result.error_details["error_code"] == "UNHANDLED_EXCEPTION"
    assert "traceback" in result.error_details


def test_agent_retry_metadata_tracking():
    """Test that retry counts from context are properly tracked in results."""
    agent = DummySpecialistAgent()
    context = AgentContext(
        workflow_id="wf-123",
        project_id="proj-456",
        prompt="Build payment gateway integration",
        retry_count=2,
        max_retries=3,
    )

    result = agent.run(context)

    assert result.success is True
    assert result.retry_count == 2


def test_artifact_draft_model_and_size():
    """Test ArtifactDraft properties, encoding, and UTF-8 size calculation."""
    content = "SELECT * FROM users;\n-- Unicode check: 🚀 ⚡"
    artifact = ArtifactDraft(
        artifact_type="erd",
        file_path="schema.sql",
        content=content,
        language="sql",
    )

    assert artifact.artifact_type == "erd"
    assert artifact.file_path == "schema.sql"
    assert artifact.language == "sql"
    assert artifact.file_size_bytes == len(content.encode("utf-8"))


def test_deterministic_mock_provider_integration():
    """Test that custom or mock providers can be passed to agents seamlessly."""
    mock_provider = DeterministicMockProvider(
        canned_responses={"architecture": "ARCHITECTURE_MOCK_PLAN"}
    )
    agent = DummySpecialistAgent(provider=mock_provider)

    assert agent.provider.provider_name == "mock"
    output = agent.provider.generate("Please generate architecture details")
    assert output == "ARCHITECTURE_MOCK_PLAN"


@pytest.mark.asyncio
async def test_agent_async_execution():
    """Test asynchronous execution path (arun) for agents."""
    agent = DummySpecialistAgent()
    context = AgentContext(
        workflow_id="wf-async-1",
        project_id="proj-async-2",
        prompt="Asynchronous agent execution test prompt",
    )

    result = await agent.arun(context)

    assert result.success is True
    assert result.agent_name == "DummySpecialistAgent"
    assert len(result.artifacts) == 1
    assert result.execution_time_ms >= 0


def test_payload_sanitizer():
    """Test that sensitive credentials, tokens, and keys are redacted from payloads."""
    raw_payload = {
        "user_email": "developer@forgeai.com",
        "api_key": "sk-live-1234567890",
        "nested": {
            "token": "bearer-jwt-token-val",
            "password": "SecretPassword123!",
            "public_id": "pub_999",
        },
        "items": [
            {"access_token": "secret_access", "name": "Item A"},
            {"secret": "top_secret_value", "safe_field": 42},
        ],
    }

    sanitized = sanitize_payload(raw_payload)

    assert sanitized["user_email"] == "developer@forgeai.com"
    assert sanitized["api_key"] == "[REDACTED]"
    assert sanitized["nested"]["token"] == "[REDACTED]"
    assert sanitized["nested"]["password"] == "[REDACTED]"
    assert sanitized["nested"]["public_id"] == "pub_999"
    assert sanitized["items"][0]["access_token"] == "[REDACTED]"
    assert sanitized["items"][0]["name"] == "Item A"
    assert sanitized["items"][1]["secret"] == "[REDACTED]"
    assert sanitized["items"][1]["safe_field"] == 42
