"use client"

import * as React from "react"
import { useState } from "react"
import { Rocket, Server, ShieldCheck, Terminal, Copy, Check, Download, FileCode, CheckCircle2 } from "lucide-react"
import { BlueprintArtifact } from "@/types"
import ArtifactViewer from "./ArtifactViewer"

interface DevOpsManifestViewerProps {
  artifacts: BlueprintArtifact[]
}

export default function DevOpsManifestViewer({ artifacts }: DevOpsManifestViewerProps) {
  // Find all relevant devops & security artifacts
  const dockerCompose = artifacts.find(
    (a) => a.file_path.includes("docker-compose") || a.artifact_type === "deployment"
  )
  const dockerfile = artifacts.find(
    (a) => a.file_path.toLowerCase().endsWith("dockerfile") || a.language === "dockerfile"
  )
  const k8s = artifacts.find(
    (a) => a.file_path.includes("k8s") || a.file_path.includes("kubernetes")
  )
  const security = artifacts.find(
    (a) => a.artifact_type === "security" || a.file_path.includes("SECURITY")
  )
  const tests = artifacts.find(
    (a) => a.artifact_type === "testing" || a.file_path.includes("test_")
  )

  const availableTabs = [
    { id: "compose", label: "Docker Compose", icon: Server, artifact: dockerCompose },
    { id: "dockerfile", label: "Dockerfile", icon: Rocket, artifact: dockerfile },
    { id: "k8s", label: "Kubernetes Manifests", icon: Terminal, artifact: k8s },
    { id: "security", label: "Security & OWASP", icon: ShieldCheck, artifact: security },
    { id: "testing", label: "CI/CD Tests", icon: FileCode, artifact: tests },
  ].filter((tab) => tab.artifact !== undefined)

  const [activeTabId, setActiveTabId] = useState<string>(
    availableTabs.length > 0 ? availableTabs[0].id : "compose"
  )

  const currentTab = availableTabs.find((t) => t.id === activeTabId) || availableTabs[0]

  return (
    <div className="flex flex-col gap-6">
      {/* Tab Navigation */}
      {availableTabs.length > 0 && (
        <div className="flex items-center gap-2 overflow-x-auto pb-2 border-b border-[#222534]">
          {availableTabs.map((tab) => {
            const Icon = tab.icon
            const isActive = activeTabId === tab.id
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTabId(tab.id)}
                className={`px-4 py-2 rounded-xl text-xs font-mono font-medium flex items-center gap-2 transition-all cursor-pointer shrink-0 ${
                  isActive
                    ? "bg-purple-600 text-white shadow-lg shadow-purple-600/30"
                    : "bg-[#141622] border border-[#222534] text-slate-400 hover:text-white hover:border-[#2f354e]"
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{tab.label}</span>
                <span className="text-[10px] px-1.5 py-0.2 rounded-full bg-white/10 text-slate-200">
                  v{tab.artifact?.version || 1}
                </span>
              </button>
            )
          })}
        </div>
      )}

      {/* Active Tab Artifact Viewer */}
      {currentTab && currentTab.artifact ? (
        <ArtifactViewer
          artifact={currentTab.artifact}
          title={currentTab.artifact.file_path}
          description={`Production infrastructure specification generated by ${currentTab.artifact.agent_type || "DevOpsAgent"}.`}
        />
      ) : (
        <div className="p-12 bg-[#12141c]/60 border border-[#222534] rounded-2xl flex flex-col items-center justify-center text-center gap-3">
          <Rocket className="w-8 h-8 text-slate-500" />
          <p className="text-xs text-slate-400 font-mono">No deployment or infrastructure manifests available.</p>
        </div>
      )}
    </div>
  )
}
