"use client"

import * as React from "react"
import { useState, useRef, KeyboardEvent, ClipboardEvent } from "react"
import { useRouter } from "next/navigation"
import { Lock, Smartphone, MessageSquare, ArrowRight, RefreshCw } from "lucide-react"

export default function TwoFactorAuthPage() {
  const router = useRouter()
  const [method, setMethod] = useState<"app" | "sms">("app")
  const [code, setCode] = useState(["", "", "", "", "", ""])
  const [isVerifying, setIsVerifying] = useState(false)
  const inputRefs = useRef<(HTMLInputElement | null)[]>([])

  const handleChange = (index: number, value: string) => {
    // Only accept numbers
    if (!/^\d*$/.test(value)) return

    const newCode = [...code]
    newCode[index] = value
    setCode(newCode)

    // Move to next input if value is entered
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus()
    }
  }

  const handleKeyDown = (index: number, e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      // Move to previous input on backspace if current is empty
      inputRefs.current[index - 1]?.focus()
    }
  }

  const handlePaste = (e: ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault()
    const pastedData = e.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6)
    
    if (pastedData) {
      const newCode = [...code]
      for (let i = 0; i < pastedData.length; i++) {
        newCode[i] = pastedData[i]
      }
      setCode(newCode)
      
      // Focus the next empty input or the last one
      const focusIndex = Math.min(pastedData.length, 5)
      inputRefs.current[focusIndex]?.focus()
    }
  }

  const handleVerify = () => {
    if (code.some(digit => digit === "")) return
    
    setIsVerifying(true)
    // Simulate verification delay
    setTimeout(() => {
      router.push("/auth-success")
    }, 1500)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0A0A0A] p-4 font-sans text-[#e4e1ec]">
      <div className="w-full max-w-[440px] bg-[#171717] border border-[#262626] rounded-2xl p-8 md:p-10 shadow-2xl relative overflow-hidden">
        
        {/* Subtle top inner glow */}
        <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-[#5856d6]/30 to-transparent"></div>
        
        {/* Header */}
        <div className="flex flex-col items-center mb-8">
          <div className="w-16 h-16 rounded-full bg-[#1f1f27] border border-[#262626] flex items-center justify-center mb-6 shadow-inner relative">
            <div className="absolute inset-0 rounded-full border border-[#5856d6]/20"></div>
            <Lock className="w-7 h-7 text-[#c2c1ff]" />
          </div>
          <h1 className="text-2xl md:text-3xl font-semibold text-white mb-3 tracking-tight">Secure Your Account</h1>
          <p className="text-sm text-[#918f9f] text-center max-w-[280px] leading-relaxed">
            Enter the 6-digit verification code generated by your authenticator app.
          </p>
        </div>

        {/* Delivery Method Toggle */}
        <div className="flex justify-center mb-8">
          <div className="inline-flex bg-[#13131a] border border-[#262626] rounded-full p-1">
            <button 
              onClick={() => setMethod("app")}
              className={`flex items-center gap-2 px-6 py-2 rounded-full text-sm font-medium transition-colors ${method === 'app' ? 'bg-[#1f1f27] text-white shadow-sm border border-[#35343c]' : 'text-[#918f9f] hover:text-[#c7c4d6] border border-transparent'}`}
            >
              <Smartphone className="w-4 h-4" />
              App
            </button>
            <button 
              onClick={() => setMethod("sms")}
              className={`flex items-center gap-2 px-6 py-2 rounded-full text-sm font-medium transition-colors ${method === 'sms' ? 'bg-[#1f1f27] text-white shadow-sm border border-[#35343c]' : 'text-[#918f9f] hover:text-[#c7c4d6] border border-transparent'}`}
            >
              <MessageSquare className="w-4 h-4" />
              SMS
            </button>
          </div>
        </div>

        {/* 6-Digit Input Grid */}
        <div className="flex justify-between gap-2 mb-8">
          {code.map((digit, index) => (
            <input
              key={index}
              ref={el => { inputRefs.current[index] = el }}
              type="text"
              inputMode="numeric"
              maxLength={1}
              value={digit}
              onChange={(e) => handleChange(index, e.target.value)}
              onKeyDown={(e) => handleKeyDown(index, e)}
              onPaste={handlePaste}
              className="w-12 h-14 md:w-14 md:h-16 text-center text-xl md:text-2xl font-semibold text-white bg-[#0F0F0F] border border-[#262626] rounded-xl focus:outline-none focus:border-[#5856d6] focus:ring-1 focus:ring-[#5856d6] transition-all shadow-inner"
            />
          ))}
        </div>

        {/* Verify Button */}
        <button 
          onClick={handleVerify}
          disabled={code.some(d => !d) || isVerifying}
          className="w-full bg-gradient-to-r from-[#5856d6] to-[#4f4ccd] hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed text-white h-12 rounded-xl text-sm font-medium flex items-center justify-center gap-2 transition-all shadow-[0_4px_14px_rgba(88,86,214,0.3)] mb-8 relative overflow-hidden"
        >
          {isVerifying ? (
            <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
          ) : (
            <>
              Verify
              <ArrowRight className="w-4 h-4" />
            </>
          )}
        </button>

        {/* Footer Actions */}
        <div className="flex items-center justify-between text-xs font-medium">
          <button className="flex items-center gap-1.5 text-[#918f9f] hover:text-white transition-colors">
            <RefreshCw className="w-3.5 h-3.5" />
            Resend Code <span className="text-[#c7c4d6] ml-1">(0:45)</span>
          </button>
          <button className="text-[#c2c1ff] hover:text-[#e4e1ec] transition-colors hover:underline underline-offset-4">
            Use Backup Code
          </button>
        </div>
        
      </div>
      
      {/* Structural Footer */}
      <div className="fixed bottom-0 w-full flex justify-center py-6 text-xs text-[#464554] pointer-events-none">
        ForgeAI Security Protocol v2.4
      </div>
    </div>
  )
}
